CREATE TABLE EJERCICIOS.ORDERS(
ID NUMBER(*,0) NOT NULL PRIMARY KEY,
AMOUNT NUMBER(8,2),
ORDER_DATE DATE,
CUSTOMER_ID NUMBER(*,0),
SALESMAN_ID NUMBER(*,0),
CONSTRAINT FK_CUSTOMER_ID_ORDERS
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMERS(ID),
CONSTRAINT FK_SALESMAN_ID_ORDERS
FOREIGN KEY (SALESMAN_ID)
REFERENCES SALESMAN(ID));


CREATE TABLE EJERCICIOS.CUSTOMERS(
ID NUMBER(*,0) NOT NULL PRIMARY KEY,
NAME VARCHAR2(255),
CITY VARCHAR2(255),
GRADE NUMBER(*,0),
SALESMAN_ID NUMBER(*,0),
CONSTRAINT FK_SALESMAN_ID_CUSTOMERS
FOREIGN KEY (SALESMAN_ID)
REFERENCES SALESMAN(ID));

DROP TABLE  EJERCICIOS.CUSTOMERS;

CREATE TABLE EJERCICIOS.SALESMAN(
ID NUMBER(*,0) NOT NULL PRIMARY KEY,
NAME VARCHAR2(255),
CITY VARCHAR2(255),
COMMISSION NUMBER(5,2);


